{
 "title": "Coolify - GLITCHTIP",
 "tags": [
  "coolify",
  "glitchtip"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "web - Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"web\"}"
    }
   ]
  },
  {
   "title": "web - CPU",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"web\"}[5m]) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "web - Memory",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"web\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "web - Network",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"web\"}[5m])",
     "legendFormat": "RX"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"web\"}[5m])",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "worker - Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"worker\"}"
    }
   ]
  },
  {
   "title": "worker - CPU",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"worker\"}[5m]) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "worker - Memory",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"worker\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "worker - Network",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"worker\"}[5m])",
     "legendFormat": "RX"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"worker\"}[5m])",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "postgres - Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"postgres\"}"
    }
   ]
  },
  {
   "title": "postgres - CPU",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"postgres\"}[5m]) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "postgres - Memory",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"postgres\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "postgres - Network",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"postgres\"}[5m])",
     "legendFormat": "RX"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"postgres\"}[5m])",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "redis - Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"redis\"}"
    }
   ]
  },
  {
   "title": "redis - CPU",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"redis\"}[5m]) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "redis - Memory",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"redis\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "redis - Network",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"redis\"}[5m])",
     "legendFormat": "RX"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{container_label_coolify_projectName=\"glitchtip\", container_label_com_docker_compose_service=\"redis\"}[5m])",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "GLITCHTIP - All Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{coolify_project=\"glitchtip\"}"
    }
   ]
  }
 ]
}