{
 "title": "Grafana Service",
 "tags": [
  "monitoring",
  "grafana"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Grafana Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"grafana\"}"
    }
   ]
  },
  {
   "title": "Grafana Resource Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"grafana\"}[5m]) * 100",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "(container_memory_usage_bytes{name=\"grafana\"} / container_spec_memory_limit_bytes{name=\"grafana\"}) * 100",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Grafana Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"grafana\"}"
    }
   ]
  }
 ]
}