{
 "title": "Loki Service",
 "tags": [
  "monitoring",
  "loki"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Loki Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"loki\"}"
    }
   ]
  },
  {
   "title": "Loki Ingestion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(loki_ingester_chunks_created_total[5m])",
     "legendFormat": "Chunks Created/s"
    },
    { "expr": "loki_ingester_streams", "legendFormat": "Active Streams" }
   ]
  },
  {
   "title": "Loki Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"loki\"}"
    }
   ]
  }
 ]
}